### ISSUE TITLE
(non primary only) emails are not reported

### ISSUE THREAD

**Issue by magnolia61** [eileenmcnaughton/org.wikimedia.unsubscribeemail#2]
Hi there, great extension, especially to help comply with EU GDPR privacy laws.
I just ran into what I believe is a small quirk.

When i have two contacts with both two emails.
Contact 1
email home (primary) = abc@gmail.com
email other = xyz@gmail.com
Contact 2
email home (primary) = def@gmail.com
email other = xyz@gmail.com

When I use this extension and search for **xyz@gmail.com** nothing is found
but when i change one of the contacts other email to primary both are found.

It seems currently when unsubscribing/opting out xyz@gmail.com has to be the primary email of at least one contact. It would be great if also results are shown when xyz@gmail.com is non-primary only

**Comment by eileenmcnaughton** [comment]
It took me a while to figure out that this was really a bug rather than a feature request :-) It turns out the emails to remove the bulk mail flag from were being retrieved but then the code to display them was nested in a block that only showed if there were contacts to opt out - so the opt out was not there. I've pushed a fix that makes it like this

![screenshot 2018-01-02 16 54 53](https://user-images.githubusercontent.com/336308/34473988-1962708e-efde-11e7-8cc3-9775a9c36f8c.png)
